  # SEACANAIRY CONFIGURATION FILE

# Recommendations
  # do not change the file syntax
  # settings must either be Yes or No
  # numbers must be integer (without decimals)
  # After changing any settings, check that the Software still work

Seacanairy settings:
  # Name of the folder in which the log and data files will be stored:
  Sampling session name: "sampling_at_the_HZS_example" #.csv
  # Amount of time between each consecutive measurement
  Sampling period: 60  # seconds
  Flushing time before measurement: 0  # seconds
  Activate M&C air pump: Yes


CO2 sensor:
  Activate this sensor: Yes
  Automatic sampling frequency (number of sample during the above sampling period): 1
  Amount of time required for the sensor to take the measurement: 10  # seconds (default value: 10 seconds)
  Store debug messages (important increase of logs): No
  Number of reading attempts: 3


OPC-N3 sensor:
  Activate this sensor: Yes
  # Amount of time at which the fan keep running to refresh the air inside the sensor casing
  Flushing time: 4
  # Amount of time at which the laser is kept on and measure the air
  # This period will be multiplied by 2 in practice because the sensor automatically take a
  # first measurement in high gain and then another one in low gain mode
  Sampling time: 4
  Fan speed: 100 # 0 = the slowest, 100 = the fastest
  # In case of data transmission error, take another sample (Yes) or
  # read the data again even if sampling time is really short (No)
  Take a new measurement if checksum is wrong (avoid shorter sampling periods when errors): Yes
  Store debug messages (important increase of logs): No


Air flow sensor:
  Activate this sensor: Yes
  Measure during OPCN3 measurement: Yes  # measure the flow rate during the Particulate Matter OPCN3 measurement
  Store debug messages (important increase of logs): No


GPS:
  Activate this sensor: Yes
  Store debug messages (important increase of logs): No


AFE Board:
  Activate this sensor: Yes
  Store debug messages (important increase of logs): No
  # Perform multiple readings and average them to reduce noise
  Noise reduction - number of reading averaged: 4